# Generated by Django 4.2.7 on 2025-09-29 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0002_add_email_and_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_id', models.UUIDField(help_text='Original ID of the worker')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for deletion')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('original_created_at', models.DateTimeField()),
                ('original_updated_at', models.DateTimeField()),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_workers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Worker Histories',
                'db_table': 'worker_history',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
