# Generated by Django 4.2.7 on 2025-09-24 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE_PRODUCT', 'Create Product'), ('UPDATE_PRODUCT', 'Update Product'), ('DELETE_PRODUCT', 'Delete Product'), ('CREATE_WORKER', 'Create Worker'), ('UPDATE_WORKER', 'Update Worker'), ('DELETE_WORKER', 'Delete Worker'), ('CREATE_PURCHASE', 'Create Purchase'), ('UPDATE_PURCHASE', 'Update Purchase'), ('CREATE_TASK', 'Create Task'), ('UPDATE_TASK', 'Update Task'), ('CREATE_DAILY_SALARY', 'Create Daily Salary'), ('CREATE_SALARY_PAYMENT', 'Create Salary Payment'), ('SELL_STOCK', 'Sell Stock'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('OTHER', 'Other Action')], max_length=50)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
